batch_size: 8
learning_rate: 0.001
dropout: 0.2
vision_model: 'videomae'
language_model: 'bert'
seq_len: 16
num_classes: 10
gt_folder: './synthetic_dataset'
freeze_visionbackbone: False
use_lora_vision: False
freeze_llmbackbone: False
use_lora_llm: False
inference: False
captioning: False
use_text: False